// Generated code for Varlink interface `io.ducky.Keystroke`.
//
// This code was generated by `zlink-codegen` from Varlink IDL.
// You may prefer to adapt it, instead of using it verbatim.

// Keystroke Interface
//
// A varlink interface for sending keystrokes and key combinations

use serde::{Deserialize, Serialize};
use zlink::{proxy, ReplyError};

/// Proxy trait for calling methods on the interface.
#[proxy("io.ducky.Keystroke")]
pub trait Keystroke {
    /// Send a single keystroke
    async fn send_key(
        &mut self,
        key: &str,
    ) -> zlink::Result<Result<SendKeyOutput<'_>, KeystrokeError>>;
    /// Send a key combination (multiple keys held together)
    async fn send_keys(
        &mut self,
        keys: &[&str],
    ) -> zlink::Result<Result<SendKeysOutput<'_>, KeystrokeError>>;
}

/// Output parameters for the SendKey method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SendKeyOutput<'a> {
    pub success: bool,
    #[serde(borrow)]
    pub key: &'a str,
}

/// Output parameters for the SendKeys method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SendKeysOutput<'a> {
    pub success: bool,
    #[serde(borrow)]
    pub keys: Vec<&'a str>,
}

/// Errors that can occur in this interface.
#[derive(Debug, Clone, PartialEq, ReplyError)]
#[zlink(interface = "io.ducky.Keystroke")]
pub enum KeystrokeError {
    /// Error returned when the key parameter is invalid
    InvalidKey { message: String },
}
